#!/usr/bin/python

import optparse
from yama import server


if __name__ == "__main__":
    PROGRAM_NAME = str(__file__)
    parser = optparse.OptionParser("usage: " + PROGRAM_NAME + " --config-file '/etc/yama/config.yaml' ")
    parser.add_option("-c", "--config-file", dest="config_file", type="string", help="specify configuration file path")

    (options, args) = parser.parse_args()
    if not options.config_file:
        parser.error('config file not given')
        exit(1)
    else:
        server = server.Server(str(options.config_file))
        server.start()
