# YAMA config file
#

# IP address to bind
host: 0.0.0.0

# Port to bind
port: 80

#### DATABASE #####
# DB hostname
db_hostname: 'localhost'

# DB username
db_username: 'yama'

# DB passwd
db_passwd: 'yama'

# DB name
db_name: 'yama'
